sys_error: allow custom error handler
The sys_error_handler variable can be set to a function to handle errors
instead of the default sys_error handling.

This is for the alice-tools GUI, so that the error message can be
displayed in a message box.